[semantic_release]
build_command = """
    pip install uv==0.5.0
    uv lock --upgrade-package "$PACKAGE_NAME"
    git add uv.lock
    uv build
"""
assets = []
build_command_env = []
commit_message = "v{version} release!"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = false
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_toml = ["pyproject.toml:project.version"]
version_variables = ["src/framex/consts.py:VERSION"]

[semantic_release.branches.main]
match = "(master|main)"
prerelease_token = "rc"
prerelease = false

[semantic_release.branches.beta]
match = "(dev)"
prerelease = true
prerelease_token = "beta"


[semantic_release.changelog]
exclude_commit_patterns = []
mode = "update"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = false

[semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "github-releaser <github-releaser>"

[semantic_release.commit_parser_options]
minor_tags = ["update"]
patch_tags = ["feat", "fix", "build", "perf", "refactor"]
allowed_tags = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "style",
  "refactor",
  "test",
  "update",
]
default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[semantic_release.remote]
name = "origin"
type = "github"
token = { env = "GH_TOKEN" }
ignore_token_for_push = false
insecure = true
url = "https://github.com/touale/FrameX-kit"
domain = "https://github.com"
