target-version = "py311"
line-length = 119

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

[lint]

extend-select = [
  "C",     # Complexity
  "E",     # PEP8 errors
  "F",     # PEP8 formatting
  "I",     # Import sorting
  "UP",    # Pyupgrade upgrades
  "W",     # PEP8 warnings
  "T201",  # print found
  "T10",   # dubug found
  "FLY",   # static-join-to-f-string
  "RET",   # unnecessary-return
  "N",     # name-conventions
  "PIE",   # Improper comments
  "SIM",   # simplify
  "ERA",   # commented-out-code
  "ASYNC", # async
  "TID",   # tidy-imports
  "A",     # bad name
  "ARG",   # bad arguments
  "PTH",   # use-pathlib
  "RUF",   # specific rules
  "B",     # flake8-bugbear.
  "PT",    # pytest
  "PERF",  # Perflint
]
ignore = [
  #    "C901", # Function too complex
  "E501",  # Line length (handled by ruff-format)
  "UP007", # X | Y style Unions
  "B008",  # Do not perform function calls in argument defaults
  "PT006", # Ignore pytest.mark.parametrize
  #    "PT011", # Ignore `pytest.raises(ValueError)` is too broad
  #    "D203", # one-blank-line-before-class
  #    "D212", # multi-line-summary-first-line
  "ERA001",
  #    "W291",
  "RUF001",
  "RET504",
  "SIM108",
  #    "PT009",
  "RUF003",
  "PTH123",
  "PTH113",
  "PTH118",
  "PTH109",
  "PTH112",
  "PTH103",
  "SIM118",
  "RUF002",
  "B006",
  "PIE810",
  "PTH107",
  "C901",
  "C416",
  "PTH120",
  "E402",   # Module level import not at top of file
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
split-on-trailing-comma = true


[lint.flake8-builtins]
builtins-ignorelist = ["input", "id", "bytes", "type"]

[lint.pydocstyle]
convention = "numpy"
