target-version = "py311"
line-length = 119
respect-gitignore = true
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

[lint]
extend-select = [
  "C",     # Complexity
  "E",     # PEP8 errors
  "F",     # PEP8 formatting
  "I",     # Import sorting
  "UP",    # Pyupgrade upgrades
  "W",     # PEP8 warnings
  "T201",  # print found
  "T10",   # dubug found
  "FLY",   # static-join-to-f-string
  "RET",   # unnecessary-return
  "N",     # name-conventions
  "PIE",   # Improper comments
  "SIM",   # simplify
  "ERA",   # commented-out-code
  "ASYNC", # async
  "TID",   # tidy-imports
  "A",     # bad name
  "ARG",   # bad arguments
  "PTH",   # use-pathlib
  "RUF",   # specific rules
  "B",     # flake8-bugbear.
  "PT",    # pytest
  "PERF",  # Perflint
  "FAST",  # FastAPI (FAST)
  "ANN",   # flake8-annotations
]
ignore = [
  "B008",   # Do not perform function calls in argument defaults
  "ERA001",
  "C901",
  "E402",   # Module level import not at top of file
  "ANN401", # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
]

[lint.flake8-builtins]
builtins-ignorelist = ["input", "id", "bytes", "type"]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
split-on-trailing-comma = true

[lint.pydocstyle]
convention = "numpy"
